config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :leads
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :leads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
  
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
    @lead = policy_scope(Lead).order(created_at: :desc)
  end

  # GET /leads/1
  # GET /leads/1.json
  def show

  end

  # GET /leads/new
  def new
    @lead = Lead.new
    authorize @lead
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)
    @lead.user = current_user
    authorize @lead

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
      authorize @lead
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.require(:lead).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>David Lusztig</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/leads/_form.html.erb
<div class="container">
<%= simple_form_for(@lead) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , class: 'bttn bttn-wide'%>
  </div>
<% end %>
</div>

app/views/leads/edit.html.erb
<div class="login-container">
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>
<br>
<%= link_to 'Show', @lead, class: "bttn"  %>
<%= link_to 'Back', leads_path, class: "bttn"  %>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/leads/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Leads</h1>

<table class="table-container">
  <thead>
    <tr>
      <th>Name of your lead</th>
      <br>
      <th>User ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</div>
  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.name %></td>
        <td><%= lead.user_id %></td>
        <td><%= link_to 'Show', lead , class: "bttn" %></td>
        <% if policy(lead).edit? %>
          <td><%= link_to 'Edit', edit_lead_path(lead), class: "bttn"  %></td>
        <% end %>
        <% if policy(lead).destroy? %>
          <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } , class: "bttn" %></td>
        <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if policy(Lead).new? %>
<%= link_to 'Create A New Lead', new_lead_path, class: "bttn" %>
<% end %>
<br>
<div>
<br>
<span class="badge badge-success">NOTE THAT ONLY IF YOU ARE LOGGED IN AS "ADMIN" WILL YOU BE ABLE TO EDIT AND DESTROY DATA</span>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br>

</div>

app/views/leads/new.html.erb
<div class="login-container">
<h1>Add a new lead</h1>

<%= render 'form', lead: @lead, class: "bttn"  %>
<br>
<%= link_to 'Back', leads_path, class: "bttn"  %>
</div>
<br><br><br><br><br><br><br><br><br><br>
<br><br><br><br>

app/views/leads/show.html.erb
<div class="login-container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @lead.user_id %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead), class: "bttn"  %> 
<%= link_to 'Back', leads_path, class: "bttn"  %>
</div>
<div>
<br>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br>

app/views/pages/home.html.erb
<%# <div class="home-banner">
  <h1>David Lusztig</h1>
  <p>
  <span id="banner-typed-text"></span>
</p> %>
<%# 
<div class="jumbotron">
  <h1 class="display-4">David Lusztig</h1>
  <p class="lead">FULL STACK DEVELOPER & SENIOR MARKETING PROFESSIONAL</p>
  <hr class="my-4">
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div> %>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">DAVID LUSZTIG</h1>
    <p class="lead">is a senior online marketing professional with full-stack web developer skills</p>
      <p>
        <span id="banner-typed-text"></span>
      </p>
      <%= link_to "Log in", new_user_session_path, class: "bttn" %>
  </div>
</div>
<br>

<div class="container">
<div class="card">
  <div class="card-header">
<h1><strong>Personal Statement & Skill Set</strong></h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">
</h5>
    <p><strong>I am a senior online marketing professional with full-stack web developer and excellent communication skills.</strong></p>
    <p>I found that combining these 3 uniques carry the potential of creating a profit-oriented, agile, dynamic, scalable, and highly transparent business function. My next challenge will ideally be to build or lead a team to success at a small or medium-sized company.
    </p>
    <p class="card-text"><strong>Commercial Skills: </strong>I have spent the past 13 years, conceiving, designing, and effectively delivering Marketing and Sales funnels, MVPs, and online products. These efforts created new profit streams for Small-Medium Companies.

</p> <p> <strong>Technical Skills: </strong>I can alone or in a team concept, plan, develop commercial projects in Ruby on Rails, Javascript, Ruby, HTML, and CSS. I am fluent in SEA, SEO, social ads, email marketing, and all related user acquisition logic, flow, and management. I am a curious and stubborn problem solver!

</p> <p> <strong>Communication Skills:</strong> I have extensive experience in building “startup-fluent" and agile commercial teams as I learned in the Israeli and International Startup scenes. I am no-nonsense, analytical, result-oriented, and a natural team-player and coach.
</p>
 <p>
  <span id="banner-typed-text"></span>
</p>
    <%= link_to "Log into my demo CRM", leads_path, class: "bttn" %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><strong>Every Business Needs A Backend</strong></h5>
        <p class="card-text">Peek inside this demo mini CRM's full power admin backend I built in 1 hour.</p>
        <p>Use these credentials and take a tour:</p>
        <p class="card-text"><strong>Email:</strong> admin@demo.com</p><p class="card-text"><strong>Password:</strong> password</p>
        <a href="https://davidlusztig.herokuapp.com/admin" class="bttn">Log in as Admin</a>
      </div>
    </div>
  </div>
  
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><strong>Anyone can have a good idea</strong></h5>
        <p class="card-text">I have the skill, the experience, and the right attitude to build a team to have any idea developed and scaled.</p>
         <a href="https://www.linkedin.com/in/lusztigdavid/" class="bttn-linkedin">Let's connect on <strong>Linkedin</strong></a>
      
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <href= class="footer-links">
    <a href="https://www.github.com/davidlusztig"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/lusztigdavid/"><i class="fab fa-linkedin"></i></a>
    <a href="https://twitter.com/muffinsisr"><i class="fab fa-twitter-square"></i></a>
    Made with <i class="fas fa-heart"> </i> by David in Rotterdam
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "emoji.jpg", alt: "David" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Leads", leads_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/davidlusztig", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "LOGIN", new_user_session_path, class: "bttn" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>